### ISSUE TITLE
Item checkin not returning any response

### ISSUE THREAD

**Issue by otuoma** [jblyberg/SipTwo#5]
It seems there is an issue with item checkin. I have the following code in express

 ```javascript
router.get('/checkin',  async (req: Request, res: Response) => {

    const item_barcode: string = `${req.query.item_barcode}`;

    if (!item_barcode) {
        return res.status(400).send("Item barcode is required");
    }
    const sipTwo = new SipTwo(sip2ConnectionOptions);
    // sipTwo.setPatron({
    //     patronIdentifier: "123456",
    //     password: "demopass"
    // });
    try {
        await sipTwo.login();
        let datetime_now = new Date(); //getFormattedDated();
        let checkinRequestDto: ICheckinRequestDto = {
            location: sip2ConnectionOptions.institutionId,
            offline: false,
            returnDate: datetime_now,
            itemIdentifier: item_barcode
        };
        const checkinResponse: ICheckinResponse = await sipTwo.requestCheckin(checkinRequestDto);
        sipTwo.connection.close();
        res.status(200).send(checkinResponse);
    } catch (e) {
        console.log(e);
        sipTwo.connection.close();
        res.status(500).send("Error: Internal Server Error");
    }
});
```

There is no response from the server, ever.  

However, if a non-existing item identifier is provided, then we get `Invalid Item` response, which is expected. 

I tested with the sip-testing-tool on the same sip server and was able to check-in the same item.

There could be an awaitable that is not being awaited and I have not been able to fix it. @jblyberg

**Comment by otuoma** [comment]
@jblyberg Below is the original error message. I made some changes locally that checks if `SipTwo.descriptor` is set before trying to get the value of `SipTwo.descriptor.value`. 

```
TypeError: Cannot read properties of undefined (reading 'authenticated')
    at SipTwo.descriptor.value (C:\projects\siptwo\node_modules\siptwo\src\lib\decorators\MessageGuard.ts:7:19)
    at SipTwo.login (C:\projects\siptwo\node_modules\siptwo\src\lib\SipTwo.ts:79:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jblyberg** [comment]
@otuoma Thanks for the report. I don't have a sip server handy at the moment. I'll have to spin up an evergreen box to work on this.

**Comment by otuoma** [comment]
Inside `CheckinRequest.js`, I made the following change to check if patronCredentials have been set before trying to read the password

From
```js
if (this.commonRequestDto.patronCredentials.password) {
            this.append('|AD');
            this.append(this.commonRequestDto.patronCredentials.password);
        }
```
To
```js
if (this.commonRequestDto.patronCredentials && this.commonRequestDto.patronCredentials.password) {
            this.append('|AD');
            this.append(this.commonRequestDto.patronCredentials.password);
        }
```

Then in `DateTimeHelpers.js`, I changed the date formatting string from 

```js
const formatSipRequestDateTime = (request_date = new Date()) => {
     return date_and_time_1.default.format(request_date, 'yyyymmdd    HHMMss');
};

```
To

```js
const formatSipRequestDateTime = (request_date = new Date()) => {
    // return date_and_time_1.default.format(request_date, 'yyyymmdd    HHMMss');
    return date_and_time_1.default.format(request_date, 'YYYYMMDD    HHMMss');
};

```
This changes the date format in my checkin request message from this `09Nyyyy18Sa    151244yyyy18Sa    151244APCPL|AOCPL|AB123456|ACTestPass22|BIN` to a properly formatted date  `09N20231223    15124420231223    151244APCPL|AOCPL|AB123456|ACTestPass22|BIN`

These changes solved the issue for me, but unfortunately I have not been able to create a PR for now.
